### PR TITLE
Add unit- and integration tests

### LINKED ISSUE #4: Add tests
The current code works for python 3.8 (I've tested it manually), but it needs many unit tests and integration tests to ensure it keeps working in the future.

### PR DESCRIPTION
**Pull request by jneeven**
Will eventually close #4. It's probably best to keep this PR open as a draft for now, and make several new PRs to this branch that add tests for the individual files. Also contains some minor improvements to the threadpool, since it was preventing the tests from ever finishing.

@ttuffin Feel free to edit this message, update the todo list and claim any items if you want (if not, I'll probably just go through them top to bottom).

TODO:
- [x] Add workflows that automatically execute the tests (@jneeven)
- [x] Setup a mattermost server inside a docker container so we can use it for integration tests (@jneeven)
- [x] Finish `unit_tests/bot_test.py` (@jneeven)
- [x] Finish `unit_tests/message_handler_test.py` (@jneeven)
- [x] Finish `unit_tests/plugins_test.py` (@jneeven)
- [x] Finish `integration_tests/test_default_plugin.py` (@jneeven)

### CODE REVIEW

**Comment by ttuffin** [comment]
@jneeven I have been away for the past week and just saw this. It looks like you're almost done with this PR?

**Comment by jneeven** [comment]
> @jneeven I have been away for the past week and just saw this. It looks like you're almost done with this PR?

Yes, almost there! I've already started on the last item in #14 , just need to add the remaining functions of the ExamplePlugin (will probably this weekend, I don't usually have a lot of time during the week). Feel free to provide feedback or make improvement PRs!

**Comment by jneeven** [comment]
@ttuffin all tests are now done and passing, do you want to review this or shall I just merge it?

**Review by attzonko — APPROVED** [review]
Looks great.

**Review by attzonko — APPROVED** [review]

**Comment by ttuffin** [comment]
Apologies @jneeven for the delayed response. It looks great, I was able to spin up the docker image and ran all tests without issue. Confirmed it works fine spinning up the image with `podman` as well. The only suggestion I have is that we try to reduce the size of the docker image, but that can be an improvement further down the track.

**Review by ttuffin — APPROVED** [review]

**Comment by jneeven** [comment]
> The only suggestion I have is that we try to reduce the size of the docker image, but that can be an improvement further down the track.

I believe it's currently around 1.3 GB, with the `mattermost-preview` being 1 GB or so, so I'm not sure how much we can shave off. Most of the test time is spent downloading though, so indeed it would be nice to further optimize this down the road if possible.

Thanks for the reviews, I'll merge this :+1:

**Pull request merged**
