### PR TITLE
Webhooks

### PR DESCRIPTION
**Pull request by jneeven**
Replaces #24 so I can easily apply fixes

### CODE REVIEW

**Comment by ttuffin** [comment]
@jneeven looks good! In regards to the exception message in function.py, I believe the exception info should be appended automatically: https://docs.python.org/3/library/logging.html#logging.exception

**Review by ttuffin — APPROVED** [review]

**Comment by jneeven** [comment]
> @jneeven looks good! In regards to the exception message in function.py, I believe the exception info should be appended automatically: https://docs.python.org/3/library/logging.html#logging.exception

You're right, I only realised this when I tried "fixing" it myself so I deleted my initial review :sweat_smile:  thanks

**Comment by jneeven** [comment]
They passed :tada:

**Comment by ttuffin** [comment]
Awesome! :partying_face:

**Pull request merged**
